### ISSUE TITLE
Change icons in Grid ActionColumn that support Font Aweasome 4 and 5

### ISSUE THREAD

**Issue by fabiomlferreira** [luyadev/luya-bootstrap4#13]
I'm using Font Aweasome 5 in my theme and the edit icon "fa-pencil-square-o" is not supported you can change to "fa-edit" that is supported in both versions

**Comment by nadar** [comment]
Hi @fabiomlferreira Thanks for the report. Your solution sounds good to me.

Would you like to send a PR? https://github.com/luyadev/luya-bootstrap4/blob/master/src/grid/ActionColumn.php#L19-L21

**Comment by fabiomlferreira** [comment]
Done
