### ISSUE TITLE
Deprecated BS4 classes.

### ISSUE THREAD

**Issue by moneyadmin** [luyadev/luya-bootstrap4#17]
In the file `luya-bootstrap4/src/views/blocks/BootstrapImageTextBlock.php` `.hidden-*` classes are mentioned, but they are [deprecated now](https://getbootstrap.com/docs/4.1/migration/#responsive-utilities), you must use `.d-*-*` classes instead.

**Comment by dev7ch** [comment]
@moneyadmin thank you for reporting, a PR would be nice :)

**Comment by nadar** [comment]
hi @moneyadmin thanks for the report. So it was deprecated in beta phase already?

**Comment by moneyadmin** [comment]
yes, starting with BS4-beta using of the block "Bootstrap 4 -> Image With Text" leads to an unpleasant result:
![image](https://user-images.githubusercontent.com/10677129/42886082-58475388-8aab-11e8-8e13-7764fe8f5ff9.png)

**Comment by nadar** [comment]
The `BootstrapImageTextBlock` is no long part of this repo. It has been moved to the legacy as its not supported anymore. https://github.com/luyadev/luya-legacy. So if you consider sending a PR or create an issue in the legacy repo this would be nice.
