### ISSUE TITLE
Image block should use LazyLoad (or at least be able to do so)

### ISSUE THREAD

**Issue by JohnnyMcWeed** [luyadev/luya-bootstrap4#28]
### What steps will reproduce the problem?
Use image block

### What is the expected result?
LazyLoad or option for it

### What do you get instead? (A Screenshot can help us a lot!)
No LazyLoad at all

**Comment by nadar** [comment]
Could you make an example?

**Comment by JohnnyMcWeed** [comment]
Currently the image block view (https://github.com/luyadev/luya-bootstrap4/blob/master/src/views/blocks/ImageBlock.php) is not using Luya's LazyLoad. This could improve the overall performance of a site.
Therefore this should be either implemented by default or having a block option to use it (https://github.com/luyadev/luya-bootstrap4/blob/master/src/blocks/ImageBlock.php). 
(Related to https://github.com/luyadev/luya/issues/2031 as "alt" and "title" attributes should be there aswell :) )

**Comment by nadar** [comment]
A configuration option would be great, yes! Would you like to send a PR?

**Comment by JohnnyMcWeed** [comment]
I'll go for it as soon as the LazyLoad is ready, so we can integrate the attributes at the same time :)
