### ISSUE TITLE
Image Block

### ISSUE THREAD

**Issue by TheMaaarc** [luyadev/luya-bootstrap4#7]
Add ImageBlock (figure) with caption possibility.

**Comment by nadar** [comment]
Perfect! Please don't forget to make a basic unit test, here you can see a good example: https://github.com/luyadev/luya-bootstrap3/blob/master/tests/blocks/ImageBlockTest.php

**Comment by TheMaaarc** [comment]
To-Do:
* Add Unit-Tests
* Translations

**Comment by TheMaaarc** [comment]
All Unit-Tests and translations integrated.
