### ISSUE TITLE
Image Text Block: Update to Bootstrap 4.0.0

### ISSUE THREAD

**Issue by dev7ch** [luyadev/luya-bootstrap4#8]
- bootstrap classes are not compatible with 4.0.0 (looks still like bs3 or bs4 alphla version)

e.g. https://github.com/luyadev/luya-bootstrap4/blob/master/src/views/blocks/BootstrapImageTextBlock.php#L15

**Comment by nadar** [comment]
I assume, we will remove this old blocks for 1.0.0 release

**Comment by nadar** [comment]
https://github.com/luyadev/luya-bootstrap4/issues/4
